#### 1.3 Billion

    Experiment 
        
        Population
        
            Sample <- Experiment --> Stats Result
                                            |
                                            |
                                            |
                                          Population Generalization
            
            
    
        

### Mean 

    Represent Center of Data (on the basis of magnitue)
    
    Total Deviation from Mean is Always Zero. (indicates mean is at the center)
    
    It is sensitive to Outliers 
    
    
    
    Outliers -> extreme low or extreme high values in data set 

### Latex 


    A notation Language
    

In [1]:
s = 0
for i in range(1, 11):
    s += i
else:
    print(s)

55


[latex](https://en.wikibooks.org/wiki/LaTeX)

this is $\alpha$ and this is $\beta$, this is inline latex

$$ \alpha \quad \beta \quad \gamma \quad \theta \quad \eta \quad \epsilon \quad \phi $$

$\left\{a\right\} $

$ \left\{\frac{x^2}{y^3}\right\} $

$( \big( \Big( \bigg( \Bigg(  ) \big ) \Big ) \bigg ) \Bigg )$

#### Normal Equation 

$a ^ b$ a raise to power b

\\$ a^b \\$

$x^2 + y^2$

$ x_1 + x_2 + x_3 $

\\$ x_1 + x_2 + x_3 $

$x_{a_0}$

$ \frac a b $

\\$ \frac a b \\$

$ \frac {(x+y)} {(x-y} $

$ \sum \limits_{i=1}^N $

\\$ \sum \limits_{i=1}^N \\$



$\bar x$

$\bar {x} = \frac {1}  {N} { \sum_{i=0}^{N} {x_i} } $

$\bar x = \frac {1} {N} \sum_{i=0}^N x_i$ 

$\bar x = \frac {1} {N} \sum \limits_{i=0}^N x_i$ 

In [ ]:
\sqrt \sigma

$ \sigma = \sqrt{\frac{1}{n}\sum\limits_{i=1}^n(x_i - \bar{x})^2} $

$ \sigma = \sqrt { \frac {1} {N} \sum\limits_{i=1}^N {(x_i - \bar x)}^2 } $

$\bar x = \frac { \text {sum of number} } { \text {total number} }$

$ f(n) =
  \begin{cases}
    n/2       & \quad \text{if } n \text{ is even}\\
    -(n+1)/2  & \quad \text{if } n \text{ is odd}\\
    0         & \quad \text {if } n \text{is zero}\\
  \end{cases}
$

$\int \limits_{i=1}^N y\, \mathrm{d}x$

### Central Tendency

    1. Mean 
    2. Median
    3. Mode 

$\bar x = \frac {\sum\limits_{i=1}^N x_i} {N}$

In [3]:
import numpy as np

#### How to create arrays using numpy 

In [6]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [7]:
print(dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [13]:
np.quantile

<function numpy.quantile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)>

In [14]:
np.median

<function numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)>

In [12]:
print(*[ f for f in dir(np.ndarray) if f[0].islower() ], sep='\n')

all
any
argmax
argmin
argpartition
argsort
astype
base
byteswap
choose
clip
compress
conj
conjugate
copy
ctypes
cumprod
cumsum
data
diagonal
dot
dtype
dump
dumps
fill
flags
flat
flatten
getfield
imag
item
itemset
itemsize
max
mean
min
nbytes
ndim
newbyteorder
nonzero
partition
prod
ptp
put
ravel
real
repeat
reshape
resize
round
searchsorted
setfield
setflags
shape
size
sort
squeeze
std
strides
sum
swapaxes
take
tobytes
tofile
tolist
tostring
trace
transpose
var
view


    Pandas -> Spredsheet
    
        Homogenous & Hetrogenous
        
        Name   age  sex  sal
        
        x      23    M    50
        y      40    F    40

    Numerical Data -> numpy, cupy (GPU)
    
    
    

Pandas 

    numpy
                 + extra functions
    matplotlib

##### Array Creation 

In [16]:
data = [ 10, 20, 40, 30, 20, 10, 9, 60]

In [17]:
print(type(data))

<class 'list'>


In [19]:
arr = np.array(data)
print(type(arr))

<class 'numpy.ndarray'>


In [22]:
print(arr)

[10 20 40 30 20 10  9 60]


In [21]:
arr.min()

9

In [23]:
arr.max()

60

In [25]:
np.quantile(arr, [0.25, 0.5, 0.75])

array([10. , 20. , 32.5])

In [27]:
arr.std()

16.699083058659237

In [29]:
arr.T

array([10, 20, 40, 30, 20, 10,  9, 60])

In [30]:
arr.var()

278.859375

In [31]:
arr.cumsum() # cf 

array([ 10,  30,  70, 100, 120, 130, 139, 199], dtype=int32)

In [34]:
arr = arr.reshape(-1, 4)

In [35]:
arr.shape

(2, 4)

In [36]:
print(arr)

[[10 20 40 30]
 [20 10  9 60]]


In [33]:
arr.size

8

In [37]:
arr.dtype

dtype('int32')

In [38]:
arr.astype(np.int64)

array([[10, 20, 40, 30],
       [20, 10,  9, 60]], dtype=int64)

In [ ]:
np.matmul() # matrix multiplication

np.multiply() # element wise

#### 7 pm 

    Central Tendency - Mean, Median, Mode
    
    Spredness - Variance, Standard Deviation, Range, Quantiles
    
    Outliers - check krte 
    
    Shape Data - Distributions -> possion, gaussian, bernouile distributions, explonantion ...
    

#### Image Processing

In [5]:
class Array:
    def __init__(self, d):
        self.size = len(d)
        self.data = d
        
a = Array([1, 2, 3, 4, 5])
print(a.size) # property / attribute

5


In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [22]:
bin(200)

'0b11001000'

In [ ]:
age -> 1, 200 ? 

In [23]:
((1000000 * 8)/1024)/1024

7.62939453125

In [21]:
((1000000 * 32)/1024)/1024

30.517578125

    Range - max - min 

    max - ? 

    min - ? 

    Range 

In [8]:
2**32

4294967296

In [32]:
(2**8)

256

In [ ]:
np.int8 # 128
np.uint8 # 255

In [31]:
(2**7) # 1 bit -> sign +-

128

In [29]:
(2**15)

32768

In [47]:
hash(5)

5

In [26]:
data = np.array([ 120, 130, 150, 170, 160, 165, 145, 135, 110, 125, 134 ],
               dtype=np.int16)
print(type(data))
print(data)
print(data.__sizeof__())

<class 'numpy.ndarray'>
[120 130 150 170 160 165 145 135 110 125 134]
118


(16*11)

(32*11)

In [44]:
print("Total no of elements: ", data.size)
print("Shape of Data: ", data.shape) # arrangement of data inside array
print("Type of Elements: ", data.dtype)
print("Dimension: ", data.ndim)
print("Data: ", data, data.data)

Total no of elements:  11
Shape of Data:  (11,)
Type of Elements:  int16
Dimension:  1
Data:  [120 130 150 170 160 165 145 135 110 125 134] <memory at 0x0000022A6FBCF580>


    Most operations will create a new array rather than updating exiting array
    
    just like Immutable, most of the time numpy array behave like immutable type 

In [37]:
data1 = data.astype(np.int32)

In [40]:
data.dtype

dtype('int16')

In [41]:
data1.dtype

dtype('int32')

In [45]:
data

array([120, 130, 150, 170, 160, 165, 145, 135, 110, 125, 134], dtype=int16)

In [46]:
data[0]

120

In [48]:
data[-6] # ? 

165

In [49]:
data[:3] # [0:n-1] 

array([120, 130, 150], dtype=int16)

In [50]:
data

array([120, 130, 150, 170, 160, 165, 145, 135, 110, 125, 134], dtype=int16)

In [51]:
data[1:7]

array([130, 150, 170, 160, 165, 145], dtype=int16)

In [52]:
print(data)

[120 130 150 170 160 165 145 135 110 125 134]


In [53]:
data[1:9:3] # ?

array([130, 160, 135], dtype=int16)

In [54]:
print(data)

[120 130 150 170 160 165 145 135 110 125 134]


In [55]:
print(data[-4:9:2])

[135]


In [56]:
data[::2] # ? 

array([120, 150, 160, 145, 110, 134], dtype=int16)

In [57]:
print(data[::-1])

[134 125 110 135 145 165 160 170 150 130 120]


In [58]:
print(data)

[120 130 150 170 160 165 145 135 110 125 134]


In [59]:
data

array([120, 130, 150, 170, 160, 165, 145, 135, 110, 125, 134], dtype=int16)

In [61]:
data[2] = 160 # mutable property 

In [62]:
data

array([120, 130, 160, 170, 160, 165, 145, 135, 110, 125, 134], dtype=int16)

In [63]:
data[-5:]

array([145, 135, 110, 125, 134], dtype=int16)

In [64]:
data[-5:] = 0 

In [65]:
data

array([120, 130, 160, 170, 160, 165,   0,   0,   0,   0,   0], dtype=int16)

In [66]:
data.mean()

82.27272727272727

In [67]:
data[:2] = data.mean()

In [68]:
data

array([ 82,  82, 160, 170, 160, 165,   0,   0,   0,   0,   0], dtype=int16)

In [71]:
data = np.array([ 120, 130, 150, 170, 160, 165, 145, 135, 110, 125, 134 ],
               dtype=np.int16)

In [72]:
data.size

11

In [70]:
print(data)

[120 130 150 170 160 165 145 135 110 125 134]


`Boolean Indexing`

In [73]:
bool_ixs = [ True, False, False, True, True, False, False, False, True, False, True]

In [74]:
data[bool_ixs]

array([120, 170, 160, 110, 134], dtype=int16)

In [75]:
data

array([120, 130, 150, 170, 160, 165, 145, 135, 110, 125, 134], dtype=int16)

In [76]:
data >= 140

array([False, False,  True,  True,  True,  True,  True, False, False,
       False, False])

In [77]:
data[data >= 140]

array([150, 170, 160, 165, 145], dtype=int16)

In [82]:
data[data < 130].size

3

    and     & (boolean and)
    
    or      | (boolearn or)
    
    not     ~ (negation )

In [84]:
cond = data >= 140

In [85]:
print(data[cond])

[150 170 160 165 145]


In [86]:
print(data[~cond])

[120 130 135 110 125 134]


In [83]:
data[data >= 140]

array([150, 170, 160, 165, 145], dtype=int16)

In [88]:
data[~(data >= 140) ]

array([120, 130, 135, 110, 125, 134], dtype=int16)

In [89]:
print(data)

[120 130 150 170 160 165 145 135 110 125 134]


print and count height of students as height should be greater than equal 130 and less than eqal 155

In [90]:
data[ (data >= 130 ) & (data <= 155)]

array([130, 150, 145, 135, 134], dtype=int16)

In [91]:
data[ (data >= 130 ) & (data <= 155)].size

5

print height of all students, height should be less than 130 or greater than 150

In [94]:
data[ (data < 130 ) | (data > 150 )]

array([120, 170, 160, 165, 110, 125], dtype=int16)

In [122]:
d = np.append(data, np.array([190, 180, 165, 200, 260, 20, 100]))

In [123]:
print(d)

[120 130 150 170 160 165 145 135 110 125 134 190 180 165 200 260  20 100]


### Replace Outlier with Median Value

    you will consider a point outlier if point is not in range mean +- 2*std

In [128]:
print(d)

[120 130 150 170 160 165 145 135 110 125 134 190 180 165 200 260  20 100]


    1. detect outlier
    2. replace them with median of data

In [129]:
np.std(d)

47.95113896869459

In [130]:
np.mean(d) + 2*np.std(d)

243.62450015961142

In [131]:
np.mean(d) - 2*np.std(d)

51.81994428483304

In [133]:
st = np.std(d) # sigma
xbar = np.mean(d) # mean
mu  = np.median(d) # median
r_out = (xbar+2*st) # +, -
l_out = (xbar-2*st)

out = d[ (d < l_out) | (d > r_out)]
print(out)
print(d)

d[(d < l_out) | (d > r_out)] = mu
print(d)

[260  20]
[120 130 150 170 160 165 145 135 110 125 134 190 180 165 200 260  20 100]
[120 130 150 170 160 165 145 135 110 125 134 190 180 165 200 147 147 100]


mean +- 2*std -> will cover 90 % values 

In [137]:
d = np.array([120, 130, 150, 170, 160, 165, 145, 135, 110, 125, 134, 
              190, 180, 165, 200, 260,  20, 100])
print(d)
d[ (d < np.mean(d)-(2*np.std(d)) ) | ( d > np.mean(d)+(2*np.std(d)))] = np.median(d)
print(d)

[120 130 150 170 160 165 145 135 110 125 134 190 180 165 200 260  20 100]
[120 130 150 170 160 165 145 135 110 125 134 190 180 165 200 147 147 100]


In [138]:
d


array([120, 130, 150, 170, 160, 165, 145, 135, 110, 125, 134, 190, 180,
       165, 200, 147, 147, 100])

In [139]:
d[[1, 4, 2, 6, 9, 0]] # slicing 

array([130, 160, 150, 145, 125, 120])

In [141]:
l = []
for var in range(3):
    l.append(int(input()))
else:
    arr = np.array(l)

1
2
3


In [142]:
arr

array([1, 2, 3])

In [145]:
arr = np.array( list(map( int, input().split() ) ))
print(arr)

5 6 8 2 3 4
[5 6 8 2 3 4]


    quan, price, sell price
    4,6000,7500
    3,500,650
    10,400,450
    50,1500,1660

In [150]:
%%writefile data.csv
quan,price,sell price
4,6000,7500
3,500,650
10,400,450
50,1500,1660

Overwriting data.csv


In [151]:
arr = np.genfromtxt('data.csv', dtype=np.int16, delimiter=',', skip_header=True)

In [152]:
arr

array([[   4, 6000, 7500],
       [   3,  500,  650],
       [  10,  400,  450],
       [  50, 1500, 1660]], dtype=int16)

In [158]:
((arr[:, 2] - arr[:, 1])*arr[:, 0] ).sum()

14950

    numpy array + Stats + Pandas Introduction

    Maplotlib + Pandas 

    Data Anayalsis 

    Data Collection

    mean, median, mode
    variance, standard deviation, Range, Quantiles
    Kurtosis, Skewness in Data
    Normal, Gaussian, Standard Normal, Binomial, Uniform, Gamma, Possion, Expontial, ... ?
    
    Histograms, Box Plot
    
    5 point Summary

In [102]:
data.std() # Spreadness

18.425637905684702

In [103]:
data.mean()

140.36363636363637

In [105]:
np.median(data)

135.0

In [106]:
np.mean(data)

140.36363636363637

In [107]:
np.var(data)

339.504132231405

In [108]:
np.std(data)

18.425637905684702

In [109]:
np.quantile(data, [0.25, .5, .75])

array([127.5, 135. , 155. ])